In [2]:
import torch
from utils.config.default import get_cfg_default
from utils.tools import *
from utils.logger import *
from utils.engine.builder import build_dataset, build_model
import dataset.demo


root="./data"
output_dir="./output/demo/PaD_TS/default/seed_1"
model="PaD_TS"
config_file = "./configs/models/PaD_TS/default.yaml"
dataset_config_file = "./configs/datasets/demo.yaml"
window = 3
seed = 1
period = "train"

2025-03-20 22:24:32.195295: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-03-20 22:24:32.316530: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-20 22:24:32.347305: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-20 22:24:32.869225: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; 

In [3]:
def extend_cfg(cfg):
    from yacs.config import CfgNode as CN

    # PAD_TS 模型的默认配置
    cfg.MODEL.PAD_TS = CN()
    cfg.MODEL.PAD_TS.HIDDEN_SIZE = 128
    cfg.MODEL.PAD_TS.NUM_HEADS = 4
    cfg.MODEL.PAD_TS.N_ENCODER = 1
    cfg.MODEL.PAD_TS.N_DECODER = 3
    cfg.MODEL.PAD_TS.FEATURE_LAST = True
    cfg.MODEL.PAD_TS.DROPOUT = 0.0
    cfg.MODEL.PAD_TS.MLP_RATIO = 4.0

cfg = get_cfg_default()
extend_cfg(cfg)
cfg.merge_from_file(dataset_config_file)
cfg.merge_from_file(config_file)
cfg.DATASET.ROOT = root
cfg.OUTPUT_DIR = output_dir
cfg.SEED = seed
cfg.MODEL.NAME = model
cfg.DATASET.WINDOW = window
cfg.DATASET.PERIOD = period
cfg.freeze()

if cfg.SEED >= 0:
        print("Setting fixed seed: {}".format(cfg.SEED))
        set_random_seed(cfg.SEED)


if torch.cuda.is_available() and cfg.USE_CUDA:
    torch.backends.cudnn.benchmark = True

Setting fixed seed: 1


In [4]:
dataset = build_dataset(cfg)
print(dataset.train["numerical"])
print(dataset.train["text"])

Loading dataset: demo
[[[ 1  6]
  [ 2  7]
  [ 3  8]]

 [[ 2  7]
  [ 3  8]
  [ 4  9]]

 [[ 3  8]
  [ 4  9]
  [ 5 10]]

 [[ 4  9]
  [ 5 10]
  [ 6 11]]

 [[ 5 10]
  [ 6 11]
  [ 7 12]]

 [[ 6 11]
  [ 7 12]
  [ 8 13]]

 [[ 7 12]
  [ 8 13]
  [ 9 14]]

 [[ 8 13]
  [ 9 14]
  [10 15]]

 [[ 9 14]
  [10 15]
  [11 16]]

 [[10 15]
  [11 16]
  [12 17]]

 [[11 16]
  [12 17]
  [13 18]]

 [[12 17]
  [13 18]
  [14 19]]

 [[13 18]
  [14 19]
  [15 20]]

 [[14 19]
  [15 20]
  [16 21]]

 [[15 20]
  [16 21]
  [17 22]]

 [[16 21]
  [17 22]
  [18 23]]

 [[17 22]
  [18 23]
  [19 24]]

 [[18 23]
  [19 24]
  [20 25]]]
[['Text 1', 'Text 2', 'Text 3'], ['Text 2', 'Text 3', 'Text 4'], ['Text 3', 'Text 4', 'Text 5'], ['Text 4', 'Text 5', 'Text 6'], ['Text 5', 'Text 6', 'Text 7'], ['Text 6', 'Text 7', 'Text 8'], ['Text 7', 'Text 8', 'Text 9'], ['Text 8', 'Text 9', 'Text 10'], ['Text 9', 'Text 10', 'Text 11'], ['Text 10', 'Text 11', 'Text 12'], ['Text 11', 'Text 12', 'Text 13'], ['Text 12', 'Text 13', 'Text 14'], ['Tex